//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduLocate.Application.Core.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EduLocate.Application.Core.I18N.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address or postcode not found..
        /// </summary>
        internal static string AddressPostcodeNotFound {
            get {
                return ResourceManager.GetString("AddressPostcodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EduLocate.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show higher education establishments.
        /// </summary>
        internal static string CollegeSchool {
            get {
                return ResourceManager.GetString("CollegeSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra school filters.
        /// </summary>
        internal static string ExtraFiltersSection {
            get {
                return ResourceManager.GetString("ExtraFiltersSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find schools.
        /// </summary>
        internal static string FindSchoolsSection {
            get {
                return ResourceManager.GetString("FindSchoolsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show mixed schools.
        /// </summary>
        internal static string GenderBoth {
            get {
                return ResourceManager.GetString("GenderBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show boys-only schools.
        /// </summary>
        internal static string GenderBoy {
            get {
                return ResourceManager.GetString("GenderBoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show girls-only schools.
        /// </summary>
        internal static string GenderGirl {
            get {
                return ResourceManager.GetString("GenderGirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genders.
        /// </summary>
        internal static string GenderSection {
            get {
                return ResourceManager.GetString("GenderSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address: .
        /// </summary>
        internal static string GeneralAddress {
            get {
                return ResourceManager.GetString("GeneralAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Stages:.
        /// </summary>
        internal static string GeneralEducationStages {
            get {
                return ResourceManager.GetString("GeneralEducationStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender: .
        /// </summary>
        internal static string GeneralGender {
            get {
                return ResourceManager.GetString("GeneralGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School information.
        /// </summary>
        internal static string GeneralInfo {
            get {
                return ResourceManager.GetString("GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating on %provider%:.
        /// </summary>
        internal static string GeneralRating {
            get {
                return ResourceManager.GetString("GeneralRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion: .
        /// </summary>
        internal static string GeneralReligion {
            get {
                return ResourceManager.GetString("GeneralReligion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone No: .
        /// </summary>
        internal static string GeneralTelephone {
            get {
                return ResourceManager.GetString("GeneralTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image courtesy of %provider%..
        /// </summary>
        internal static string ImageProvidedBy {
            get {
                return ResourceManager.GetString("ImageProvidedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        internal static string KilometersUnit {
            get {
                return ResourceManager.GetString("KilometersUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing location permissions. Try enabling them in the settings..
        /// </summary>
        internal static string LocationFeatureMissingPermission {
            get {
                return ResourceManager.GetString("LocationFeatureMissingPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location features are disabled on this device..
        /// </summary>
        internal static string LocationFeaturesDisabledOnDevice {
            get {
                return ResourceManager.GetString("LocationFeaturesDisabledOnDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location features are not supported on this device..
        /// </summary>
        internal static string LocationFeaturesNotSupportedOnDevice {
            get {
                return ResourceManager.GetString("LocationFeaturesNotSupportedOnDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location feature has encountered an error. Please try again or use an alternative option..
        /// </summary>
        internal static string LocationUnknownError {
            get {
                return ResourceManager.GetString("LocationUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on a pin, then on the name that pops up to view a school&apos;s information..
        /// </summary>
        internal static string MapPageHelp {
            get {
                return ResourceManager.GetString("MapPageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one gender option must be selected..
        /// </summary>
        internal static string MustSelectAtLeastOneGenderError {
            get {
                return ResourceManager.GetString("MustSelectAtLeastOneGenderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one religion option must be selected..
        /// </summary>
        internal static string MustSelectAtLeastOneReligionError {
            get {
                return ResourceManager.GetString("MustSelectAtLeastOneReligionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one education stage must be selected..
        /// </summary>
        internal static string MustSelectAtLeastOneStageError {
            get {
                return ResourceManager.GetString("MustSelectAtLeastOneStageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No schools found.
        /// </summary>
        internal static string NoSchoolsFoundError {
            get {
                return ResourceManager.GetString("NoSchoolsFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not provided..
        /// </summary>
        internal static string NotProvided {
            get {
                return ResourceManager.GetString("NotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %found% schools found..
        /// </summary>
        internal static string NumberOfSchoolsFound {
            get {
                return ResourceManager.GetString("NumberOfSchoolsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Ofsted Inspection.
        /// </summary>
        internal static string OfstedInfo {
            get {
                return ResourceManager.GetString("OfstedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating: .
        /// </summary>
        internal static string OfstedRating {
            get {
                return ResourceManager.GetString("OfstedRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string OfstedRatingDate {
            get {
                return ResourceManager.GetString("OfstedRatingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Filters.
        /// </summary>
        internal static string OpenExtraFilters {
            get {
                return ResourceManager.GetString("OpenExtraFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Science Square, NE4 5TG.
        /// </summary>
        internal static string PostcodePlaceholder {
            get {
                return ResourceManager.GetString("PostcodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show primary schools.
        /// </summary>
        internal static string PrimarySchool {
            get {
                return ResourceManager.GetString("PrimarySchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pupil information.
        /// </summary>
        internal static string PupilInfo {
            get {
                return ResourceManager.GetString("PupilInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent boys: .
        /// </summary>
        internal static string PupilStatsBoys {
            get {
                return ResourceManager.GetString("PupilStatsBoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent girls: .
        /// </summary>
        internal static string PupilStatsGirls {
            get {
                return ResourceManager.GetString("PupilStatsGirls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money spent per pupil (£): .
        /// </summary>
        internal static string PupilStatsMoneySpent {
            get {
                return ResourceManager.GetString("PupilStatsMoneySpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of pupils: .
        /// </summary>
        internal static string PupilStatsTotal {
            get {
                return ResourceManager.GetString("PupilStatsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        internal static string ReligionSection {
            get {
                return ResourceManager.GetString("ReligionSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Apply.
        /// </summary>
        internal static string SaveExtraFilters {
            get {
                return ResourceManager.GetString("SaveExtraFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education stages.
        /// </summary>
        internal static string SchoolTypeToSearch {
            get {
                return ResourceManager.GetString("SchoolTypeToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search radius: .
        /// </summary>
        internal static string SearchRadiusKM {
            get {
                return ResourceManager.GetString("SearchRadiusKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show secondary schools.
        /// </summary>
        internal static string SecondarySchool {
            get {
                return ResourceManager.GetString("SecondarySchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show ron-religious schools.
        /// </summary>
        internal static string ShowNonReligious {
            get {
                return ResourceManager.GetString("ShowNonReligious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show religious schools.
        /// </summary>
        internal static string ShowReligion {
            get {
                return ResourceManager.GetString("ShowReligion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Device Location.
        /// </summary>
        internal static string UseDeviceLocation {
            get {
                return ResourceManager.GetString("UseDeviceLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Address/Postcode.
        /// </summary>
        internal static string UsePostcodeForLocation {
            get {
                return ResourceManager.GetString("UsePostcodeForLocation", resourceCulture);
            }
        }
    }
}
